"""Small shell-output helpers used by the launcher config compiler.

这个模块只处理“写给 Bash source 的文件”这一件事。Python compiler 会把
最终环境变量写成 `export NAME='value'` 的形式，launcher 继续 source 这个文件
再启动服务和训练。因此这里必须非常保守：变量名只接受 shell identifier，变量值
统一用 `shlex.quote` 转义，避免空格、逗号、引号等字符破坏后续 Bash 解析。
"""

from __future__ import annotations

import re
import shlex
from pathlib import Path
from typing import Mapping

_SHELL_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def shell_quote(value: object | None) -> str:
    """把单个标量值转成 Bash 安全 token。"""

    if value is None:
        text = ""
    else:
        text = str(value)
    return shlex.quote(text)


def write_export_file(path: Path, values: Mapping[str, object | None]) -> None:
    """写入可被 Bash `source` 的 export 文件。

    文件格式刻意保持简单：一行一个 `export NAME=value`。不支持数组、命令替换或
    heredoc，因为 compiler 的边界是 Python 决定最终值，Bash 只消费已经物化的值。
    """

    lines = [
        "# Generated by scripts/coagenticRetriever_v2/assets/trainer_launcher/compile_config.py",
        "# Source this file from Bash; do not edit it by hand.",
    ]
    for name, value in values.items():
        if not _SHELL_IDENTIFIER_RE.match(name):
            raise ValueError(f"invalid shell variable name: {name!r}")
        lines.append(f"export {name}={shell_quote(value)}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
