main_run:
  project:
    experiment_name: agentic_iter_rag_v1_spad_qwen3_1_7b_newdata_512

data:
  train_files:
    - /data01/ms_wksp/agent_up_to_date/CoSearch_derevitives/data/global_train_eval_data/512t/co_search_ablation.train.parquet
  val_files:
    - /data01/ms_wksp/agent_up_to_date/CoSearch_derevitives/data/global_train_eval_data/350e/co_search_ablation.eval.parquet
  train_max_samples: 512
  val_max_samples: 8

agent_training:
  reward:
    type: spad_em_teacher_backoff
  sub_stages:
    search_policy_rl:
      trainer:
        total_training_steps: 8
        train_max_samples: 512
        save_freq: 8
        data_seed: 42
    answer_refresh_data:
      inputs:
        max_samples: 512
    answer_distillation:
      phases:
        grpo:
          experiment_name: spad_newdata_512_stage3_grpo
          data_seed: 42

